{
    "DESIGN_NAME": "synchronizer",
    "CLOCK_PORT": ["clk_r", "clk_w"],
    "VERILOG_FILES": "dir::/rtl/*v", 
    "PNR_SDC_FILE": "dir::constraints.sdc", # contains clock information
    "SIGNOFF_SDC_FILE": "dir::constraints.sdc",
    "PL_RESIZER_MAX_SLEW_MARGIN": 30, # maybe stops MaxSlewVioations. def: 20
    "SYNTH_MAX_FANOUT": 6, # stops MaxCapViolations at the cost of area (didn't work)
    "CLOCK_BUFFER_FANOUT": 6, # (same as above..., this fix actually seemed to fix the issue)
    "FP_PDN_VOFFSET": 7,
    "FP_PDN_HOFFSET": 7,
    "FP_PDN_SKIPTRIM": true,
    "RUN_POST_GRT_RESIZER_TIMING": true,
    "RUN_POST_GRT_DESIGN_REPAIR": true,
    "SYNTH_AUTONAME": true # Use to keep names consistent w/ my design's. Turn off for large designs.
}